version: "3.8"

services:
  db:
    image: postgres:14
    container_name: tasksphere_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: TaskSphere
    volumes:
      - tasksphere-db-data:/var/lib/postgresql/data  #PostgreSQL won't lose data

  backend:
    build: ./backend
    container_name: tasksphere_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypass@db:5432/TaskSphere
      SECRET_KEY: supersecretkey123
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: tasksphere_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  tasksphere-db-data:

#db: is the service name and Docker Compose gives you internal DNS for free (e.g. backend can reach db by name)
